spring.application.name=servlet
# 운영 서버에서는 아래와 같은 방식의 로깅은 성능 저하를 일으키기 때문에 개발 단계에서만 사용
# 운영 서버에 맞는 로깅 방법은 이 이외에 좋은 방법이 있다(추후 학습 예정)
logging.level.org.apache.coyote.http11=trace

# 이렇게 설정해주면 스프링 부트가 @Configuration, @Bean을 이용하여 뷰 리졸브 객체를 만들어 준다.
spring.mvc.view.prefix=/WEB-INFO/views/
spring.mvc.view.suffix=.jsp